class WeatherStatusGroup {
  final Map<String, String> weatherGroups = {
    "Sunny": "sunny",
    "Clear": "clear",
    "Partly cloudy": "clear",
    "Cloudy": "clear",
    "Overcast": "clear",
    "Mist": "clear",
    "Patchy rain possible": "rain",
    "Patchy snow possible": "snow",
    "Patchy sleet possible": "snow",
    "Patchy freezing drizzle possible": "rain",
    "Thundery outbreaks possible": "rain",
    "Blowing snow": "snow",
    "Blizzard": "snow",
    "Fog": "clear",
    "Freezing fog": "clear",
    "Patchy light drizzle": "rain",
    "Light drizzle": "rain",
    "Freezing drizzle": "rain",
    "Heavy freezing drizzle": "rain",
    "Patchy light rain": "rain",
    "Light rain": "rain",
    "Moderate rain at times": "rain",
    "Moderate rain": "rain",
    "Heavy rain at times": "rain",
    "Heavy rain": "rain",
    "Light freezing rain": "rain",
    "Moderate or heavy freezing rain": "rain",
    "Light sleet": "snow",
    "Moderate or heavy sleet": "snow",
    "Patchy light snow": "snow",
    "Light snow": "snow",
    "Patchy moderate snow": "snow",
    "Moderate snow": "snow",
    "Patchy heavy snow": "snow",
    "Heavy snow": "snow",
    "Ice pellets": "snow",
    "Light rain shower": "rain",
    "Moderate or heavy rain shower": "rain",
    "Torrential rain shower": "rain",
    "Light sleet showers": "snow",
    "Moderate or heavy sleet showers": "snow",
    "Light snow showers": "snow",
    "Moderate or heavy snow showers": "snow",
    "Light showers of ice pellets": "snow",
    "Moderate or heavy showers of ice pellets": "snow",
    "Patchy light rain with thunder": "rain",
    "Moderate or heavy rain with thunder": "rain",
    "Patchy light snow with thunder": "snow",
    "Moderate or heavy snow with thunder": "snow"
  };
}
